data:
- url: 'https://github.com/MichaelBiegluk/Core-io-operations-learning/issues/39'
  title: 'New Issue Draft'
  repository: 'MichaelBiegluk/Core-io-operations-learning'
  number: 39
  state: 'open'
